name: Daily 3AM IPTV Filter Update

on:
  schedule:
    - cron: '22 13 * * *' # Fires at 9:17 PM UTC (2:47 AM IST)
  workflow_dispatch: # Allows you to run it manually anytime for testing!

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v6

      - name: Setup Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Run Filter Script
        run: python filter.py

      - name: Commit and Push Clean Playlist
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add custom_tv.m3u
          git commit -m "Automated Daily 3AM Filter Update" || exit 0
          git push
